on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build image
        run: docker build -t portfoli-app .

      - name: list images
        run: docker images



          